name: pfl_docvqa
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge

dependencies:
  - wandb
  - python
  - pytorch::pytorch=1.10
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.0
  - sentencepiece
  - huggingface::transformers=4.26.1
  - editdistance
  - flwr=1.4.0
