save_dir: save/
model_name: VT5
# model_weights: t5-base
# model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
model_weights: rubentito/t5-base-mpdocvqa
max_source_length: 512
device: cuda

visual_module:
  model: 'dit'  # 'vit' / 'dit'
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000

fl_parameters:
  sample_clients: 2
  total_clients: 3  # 10 <=== Eventually will become 10 and MUST not be modified.
  num_rounds: 100
  iterations_per_fl_round: 1

dp_parameters:
  providers_per_fl_round: 50
  sensitivity: 0.5  # [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
  noise_multiplier: 1.182
  client_sampling_probability: 0.1960
