save_dir: save/
model_name: VT5
model_weights: /SSD2/PFL-DocVQA Checkpoints/vt5_mp-docvqa.ckpt
# model_weights: /data/shared/PFL-DocVQA/Checkpoints/vt5_mp-docvqa.ckpt
max_input_tokens: 512
device: cuda
seed: 42

visual_module:
  model: dit
  model_weights: microsoft/dit-base-finetuned-rvlcdip
  finetune: False

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 10
  # warmup_iterations: 1000

fl_parameters:
  sample_clients: 2
  total_clients: 10
  num_rounds: 50
  iterations_per_fl_round: 1

dp_parameters:
  providers_per_fl_round: 50
  sensitivity: 0.5  # [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
  noise_multiplier: 1.182
