dataset_name: DocILE-ELSA
imdb_dir: /data/shared/DocILE/elsa_imdb
# imdb_dir: /data/users/rperez/DocILE/elsa_imdb
images_dir: /data/shared/DocILE/images
# images_dir: /data/users/rperez/DocILE/images
provider_docs: /data/shared/DocILE/elsa_imdb/data_points.json
