dataset_name: PFL-DocVQA
imdb_dir: /SSD/Datasets/DocILE/elsa_imdb
# images_dir: /SSD/Datasets/DocILE/images
images_dir: /SSD/Datasets/DocILE/images
provider_docs: /SSD/Datasets/DocILE/elsa_imdb/data_points.json
